=== not-louis-239/digit-recognition/data/config.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "logit_gain": {
            "type": "number",
            "minimum": 0
        },
        "image_size": {
            "type": "integer",
            "minimum": 1
        },
        "new_param_range": {
            "type": "number",
            "minimum": 0
        },
        "neurons_per_hidden_layer": {
            "type": "integer",
            "minimum": 1
        },
        "num_hidden_layers": {
            "type": "integer",
            "minimum": 1
        },
        "population_size": {
            "type": "integer",
            "minimum": 5
        },
        "base_selection_pressure": {
            "type": "number",
            "minimum": 1
        },
        "mutation_milestones": {
            "type": "array",
            "items": {
                "type": "array",
                "items": [
                    {
                        "type": "integer",
                        "description": "The generation or step index.",
                        "minimum": 0
                    },
                    {
                        "type": "number",
                        "description": "The mutation rate associated with this milestone.",
                        "minimum": 0
                    }
                ],
                "minItems": 2,
                "maxItems": 2
            }
        }
    }
}

=== not-louis-239/digit-recognition/data/config.json
{
  "$schema": "./config.schema.json",
  "logit_gain": 0.25,
  "image_size": 28,
  "new_param_range": 0.1,
  "neurons_per_hidden_layer": 100,
  "num_hidden_layers": 2,
  "population_size": 50,
  "base_selection_pressure": 24,
  "mutation_milestones": [
    [0, 0.03],
    [500, 0.02],
    [1000, 0.01],
    [1500, 0.005],
    [2000, 0.002],
    [2500, 0.00125],
    [3000, 0.00008]
  ]
}
